### ISSUE TITLE
invalid use of css

### ISSUE THREAD

**Issue by danmarsden** [mihuasi/moodle-local_good_habits#2]
As mentioned previously in CONTRIB-7231

all css for your plugin should sit within a styles.css file within the root of your plugin and it also needs to be more specific than it currently is. Moodle will automatically add a class "path-local-good_habits" to all pages loaded within /local/good_habits so examples like this from your css:
```
header .main-menu {
    float: left;
    margin-top: -10px;
}

.calendar {
    margin-top: -8px;
}
```
Should be more like this:
```
.path-local-good_habits header .main-menu {
    float: left;
    margin-top: -10px;
}

.path-local-good_habits .calendar {
    margin-top: -8px;
}
```

Please move your css into a styles.css file in the root of the plugin and also make sure you include that prefix in all css you define.

**Comment by mihuasi** [comment]
This has now been fixed - https://travis-ci.org/github/mihuasi/moodle-local_good_habits/jobs/662061630. I have shifted the general css for the feature to local/good_habits/styles.css. There is still separate css styling held in: local/good_habits/talentgrid/talentgrid-test.css. This defines the styles that are relevant to the Grid that is used. I think it makes more sense to keep these separate.
